dictionaries = ["en_us"]
words = [
    "aff",
    "allowlist",
    "cspell",
    "declarator",
    "dic",
    "eget",
    "flamegraph",
    "musl",
    "neovim",
    "pacman",
    "pyright",
    "scm",
    "spellbook",
    "vscode",
    "wooorm",
    "wrooom",
    "xdg",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
ignore_patterns = ['\b[ATCG]+\b']
